### PR TITLE
feat(*): support --skip-verify with http1

### PR DESCRIPTION
**Pull request by hanshuebner**

### CODE REVIEW

**Review by ms2008 — APPROVED** [review]
LGTM

**Comment by hanshuebner** [comment]
> LGTM

@ms2008 Can you approve?

**Comment by ms2008** [comment]
> @ms2008 Can you approve?

@hanshuebner It's approved, but I don't have the write or admin permissions for this repository, so my review is denoted with a gray check mark.

**Comment by hanshuebner** [comment]
@ms2008 Thanks!

**Pull request merged**
